---
- key: climate_relevant_co2_biomass_gas_present
  step_value: 0.1
  unit: "%"
  interface_group: present
  command_type: value
  position: 1
  slide_key: supply_co2_emissions_biomass
- key: climate_relevant_co2_biomass_liquid_present
  step_value: 0.1
  unit: "%"
  interface_group: present
  command_type: value
  position: 2
  slide_key: supply_co2_emissions_biomass
- key: climate_relevant_co2_biomass_solid_present
  step_value: 0.1
  unit: "%"
  interface_group: present
  command_type: value
  position: 3
  slide_key: supply_co2_emissions_biomass
- key: climate_relevant_co2_biomass_gas_future
  step_value: 0.1
  unit: "%"
  interface_group: future
  command_type: value
  position: 4
  slide_key: supply_co2_emissions_biomass
- key: climate_relevant_co2_biomass_liquid_future
  step_value: 0.1
  unit: "%"
  interface_group: future
  position: 5
  slide_key: supply_co2_emissions_biomass
- key: climate_relevant_co2_biomass_solid_future
  step_value: 0.1
  unit: "%"
  interface_group: future
  command_type: value
  position: 6
  slide_key: supply_co2_emissions_biomass
