---
- key: energy_mixer_for_gas_power_fuel_bio_oil_share
  share_group: energy_sector_gas
  step_value: 0.1
  unit: "%"
  interface_group: gas_fired_chp
  position: 4
  slide_key: supply_biomass_bio_coal_bio_oil
- key: co_firing_biocoal_share
  share_group: coal_plant_fuel
  step_value: 0.1
  unit: "%"
  interface_group: coal_plant
  position: 2
  slide_key: supply_biomass_bio_coal_bio_oil
- key: co_firing_coal_share
  share_group: coal_plant_fuel
  step_value: 0.1
  unit: "%"
  interface_group: coal_plant
  position: 1
  slide_key: supply_biomass_bio_coal_bio_oil
- key: energy_mixer_for_gas_power_fuel_natural_gas_share
  share_group: energy_sector_gas
  step_value: 0.1
  unit: "%"
  interface_group: gas_fired_chp
  position: 3
  slide_key: supply_biomass_bio_coal_bio_oil
- key: energy_mixer_for_gas_power_fuel_crude_oil_share
  share_group: energy_sector_gas
  step_value: 0.1
  unit: "%"
  interface_group: gas_fired_chp
  position: 5
  slide_key: supply_biomass_bio_coal_bio_oil
