---
- key: costs_wacc_households
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: costs_wacc
- key: costs_wacc_public_infrastructure
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: costs_wacc
- key: costs_wacc_proven_technologies
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: costs_wacc
- key: costs_wacc_unproven_technologies
  step_value: 0.1
  unit: "%"
  position: 4
  slide_key: costs_wacc
