---
- key: costs_imported_heat
  step_value: 0.1
  unit: "€/GJ"
  position: 8
  slide_key: costs_residual_heat
- key: costs_industry_residual_heat
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: costs_residual_heat
