---
- key: costs_hydrogen_transport_compressed_trucks
  step_value: 0.1
  unit: "€/MWh"
  position: 2
  slide_key: costs_hydrogen_transport
- key: costs_hydrogen_transport_pipelines
  step_value: 0.1
  unit: "€/MWh"
  position: 1
  slide_key: costs_hydrogen_transport
