---
- id: 1
  key: overview
  position: 1
- id: 2
  key: demand
  position: 2
- id: 3
  key: supply
  position: 3
- id: 4
  key: costs
  position: 5
- id: 5
  key: flexibility
  position: 4
  dependent_on: has_electricity_storage
- id: 6
  key: data
  position: 6
- id: 7
  key: targets
  position: 0
  dependent_on: _always_hidden
