---
- key: industry_other_metals_process_electricity_efficiency
  step_value: 0.1
  unit: "%"
  interface_group: efficiency
  position: 2
  slide_key: demand_industry_other_metals
- key: industry_other_metals_process_heat_useable_heat_efficiency
  step_value: 0.1
  unit: "%"
  interface_group: efficiency
  position: 3
  slide_key: demand_industry_other_metals
- key: industry_other_metals_production
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: demand_industry_other_metals
