---
- label: electricity_stored_in_household_batteries
  color: "#dd33cc"
  order_by: 100
  group: 
  show_at_first:
  is_target_line: 
  target_line_position: 
  gquery: households_flexibility_p2p_electricity_storage_curve
  is_1990: 
  dependent_on: 
  output_element_key: flexibility_hourly_p2p_storage
  key: electricity_stored_in_household_batteries_flexibility_hourly_p2p_storage
- label: electricity_stored_in_EV
  color: "#dd77bb"
  order_by: 110
  group: 
  show_at_first:
  is_target_line: 
  target_line_position: 
  gquery: transport_car_flexibility_p2p_electricity_storage_curve
  is_1990: 
  dependent_on: 
  output_element_key: flexibility_hourly_p2p_storage
  key: electricity_stored_in_EV_flexibility_hourly_p2p_storage
- label: energy_flexibility_pumped_storage_electricity
  color: "#416B86"
  order_by: 120
  group: 
  show_at_first:
  is_target_line: 
  target_line_position: 
  gquery: energy_flexibility_pumped_storage_electricity_storage_curve
  is_1990: 
  dependent_on: 
  output_element_key: flexibility_hourly_p2p_storage
  key: energy_flexibility_pumped_storage_electricity_flexibility_hourly_p2p_storage
- label: electricity_stored_in_mv_batteries
  color: "#5a7bc4"
  order_by: 130
  group: 
  show_at_first:
  is_target_line: 
  target_line_position: 
  gquery: energy_flexibility_mv_batteries_electricity_storage_curve
  is_1990: 
  dependent_on: 
  output_element_key: flexibility_hourly_p2p_storage
  key: electricity_stored_in_mv_batteries_flexibility_hourly_p2p_storage
- label: electricity_stored_in_opac
  color: "#385ba6"
  order_by: 140
  group: 
  show_at_first:
  is_target_line: 
  target_line_position: 
  gquery: energy_flexibility_hv_opac_electricity_storage_curve
  is_1990: 
  dependent_on: 
  output_element_key: flexibility_hourly_p2p_storage
  key: electricity_stored_in_opac_flexibility_hourly_p2p_storage
