---
- label: excess_peak
  color: "blue"
  order_by: 100
  group: electricity
  is_target_line: true
  gquery: electricity_imbalance_inflexible_excess_peak
  output_element_key: installed_flexible_capacities
  key: excess_peak_electricity_installed_flexible_capacities
- label: shortage_peak
  color: "red"
  order_by: 105
  group: electricity
  is_target_line: true
  gquery: electricity_imbalance_inflexible_shortage_peak
  output_element_key: installed_flexible_capacities
  key: shortage_peak_electricity_installed_flexible_capacities
- label: export_interconnection
  color: "#77bbdd"
  order_by: 120
  group: electricity
  is_target_line: false
  gquery: electricity_demand_flexible_export_capacity
  output_element_key: installed_flexible_capacities
  key: export_interconnection_electricity_installed_flexible_capacities
- label: power_to_heat
  color: "#F6E58D"
  order_by: 121
  group: electricity
  is_target_line: false
  gquery: electricity_demand_flexible_power_to_heat_capacity
  output_element_key: installed_flexible_capacities
  key: power_to_heat_electricity_installed_flexible_capacities
- label: power_to_hydrogen
  color: "#dd9977"
  order_by: 122
  group: electricity
  is_target_line: false
  gquery: electricity_demand_flexible_power_to_hydrogen_capacity
  output_element_key: installed_flexible_capacities
  key: power_to_hydrogen_electricity_installed_flexible_capacities
- label: power_to_power
  color: "#dd77bb"
  order_by: 123
  group: electricity
  is_target_line: false
  gquery: electricity_demand_flexible_storage_capacity
  output_element_key: installed_flexible_capacities
  key: power_to_power_input_electricity_installed_flexible_capacities
- label: coal_to_power
  color: "#000000"
  order_by: 140
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_coal_to_power_capacity
  output_element_key: installed_flexible_capacities
  key: coal_to_power_electricity_installed_flexible_capacities
- label: gas_to_power
  color: "#969696"
  order_by: 142
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_gas_to_power_capacity
  output_element_key: installed_flexible_capacities
  key: gas_to_power_electricity_installed_flexible_capacities
- label: hydrogen_to_power
  color: "#a3def7"
  order_by: 141
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_hydrogen_to_power_capacity
  output_element_key: installed_flexible_capacities
  key: hydrogen_to_power_electricity_installed_flexible_capacities
- label: import_interconnection
  color: "#77bbdd"
  order_by: 144
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_import_capacity
  output_element_key: installed_flexible_capacities
  key: import_interconnection_electricity_installed_flexible_capacities
- label: nuclear_to_power
  color: "#fd8d3c"
  order_by: 146
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_nuclear_to_power_capacity
  output_element_key: installed_flexible_capacities
  key: nuclear_to_power_electricity_installed_flexible_capacities
- label: oil_to_power
  color: "#7f2704"
  order_by: 148
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_oil_to_power_capacity
  output_element_key: installed_flexible_capacities
  key: oil_to_power_electricity_installed_flexible_capacities
- label: power_to_power
  color: "#dd77bb"
  order_by: 150
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_storage_capacity
  output_element_key: installed_flexible_capacities
  key: power_to_power_output_electricity_installed_flexible_capacities
- label: waste_to_power
  color: "#006266"
  order_by: 152
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_waste_to_power_capacity
  output_element_key: installed_flexible_capacities
  key: waste_to_power_electricity_installed_flexible_capacities
- label: wood_pellets_to_power
  color: "#6AB04C"
  order_by: 154
  group: electricity
  is_target_line: false
  gquery: electricity_production_flexible_wood_pellets_to_power_capacity
  output_element_key: installed_flexible_capacities
  key: wood_pellets__to_power_electricity_installed_flexible_capacities


- label: excess_peak
  color: "blue"
  order_by: 300
  group: hydrogen
  is_target_line: true
  gquery: hydrogen_imbalance_inflexible_excess_peak
  output_element_key: installed_flexible_capacities
  key: excess_peak_hydrogen_installed_flexible_capacities
- label: shortage_peak
  color: "red"
  order_by: 305
  group: hydrogen
  is_target_line: true
  gquery: hydrogen_imbalance_inflexible_shortage_peak
  output_element_key: installed_flexible_capacities
  key: shortage_peak_hydrogen_installed_flexible_capacities
- label: energy_hydrogen_flexibility_p2g_electricity
  color: "#dd9977"
  order_by: 320
  group: hydrogen
  is_target_line: false
  gquery: hydrogen_production_flexible_power_to_hydrogen_capacity
  output_element_key: installed_flexible_capacities
  key: power_to_hydrogen_hydrogen_installed_flexible_capacities
