---
- id: 253
  key: costs_hydrogen_import
  position: 1
  sidebar_item_key: costs_hydrogen
  output_element_key: hydrogen_cost_capacity
- id: 254
  key: costs_hydrogen_storage
  position: 2
  sidebar_item_key: costs_hydrogen
  output_element_key: breakdown_of_total_costs
- id: 255
  key: costs_hydrogen_transport
  position: 3
  sidebar_item_key: costs_hydrogen
  output_element_key: breakdown_of_total_costs
