---
- id: 45
  general_sub_header: electricity output
  key: supply_electricity_coal_plants
  position: 1
  sidebar_item_key: electricity
  alt_output_element_key: source_of_electricity_production
  output_element_key: source_of_electricity_production
- id: 46
  general_sub_header: electricity output
  key: supply_electricity_gas_plants
  position: 2
  sidebar_item_key: electricity
  alt_output_element_key: source_of_electricity_production
  output_element_key: source_of_electricity_production
- id: 47
  key: supply_electricity_oil_plants
  position: 3
  sidebar_item_key: electricity
  alt_output_element_key: source_of_electricity_production
  output_element_key: source_of_electricity_production
- id: 48
  key: supply_electricity_nuclear_plant
  position: 4
  sidebar_item_key: electricity
  alt_output_element_key: source_of_electricity_production
  output_element_key: source_of_electricity_production
