---
- id: 143
  key: fce_coal
  position: 2
  sidebar_item_key: fce
  alt_output_element_key: fuel_chain_emissions
  output_element_key: fuel_chain_emissions
- id: 144
  key: fce_gas
  position: 4
  sidebar_item_key: fce
  alt_output_element_key: fuel_chain_emissions
  output_element_key: fuel_chain_emissions
- id: 145
  key: fce_oil
  position: 3
  sidebar_item_key: fce
  alt_output_element_key: fuel_chain_emissions
  output_element_key: fuel_chain_emissions
- id: 146
  key: fce_uranium
  position: 8
  sidebar_item_key: fce
  alt_output_element_key: fuel_chain_emissions_scaled_for_uranium
  output_element_key: fuel_chain_emissions_scaled_for_uranium
- id: 147
  key: fce_biomass
  position: 7
  sidebar_item_key: fce
  alt_output_element_key: fuel_chain_emissions_scaled_for_greengas
  output_element_key: fuel_chain_emissions_scaled_for_greengas
- id: 148
  key: fce_greengas
  position: 6
  sidebar_item_key: fce
  alt_output_element_key: fuel_chain_emissions_scaled_for_greengas
  output_element_key: fuel_chain_emissions_scaled_for_greengas
- id: 158
  key: fce_settings
  position: 1
  sidebar_item_key: fce
  alt_output_element_key: fuel_chain_emissions
  output_element_key: fuel_chain_emissions
- id: 164
  key: fce_liquid_biofuels
  position: 5
  sidebar_item_key: fce
  alt_output_element_key: fuel_chain_emissions_scaled_for_liquid_biofuels
  output_element_key: fuel_chain_emissions_scaled_for_liquid_biofuels
- id: 192
  key: fce_lng
  position: 5
  dependent_on: _always_hidden
  sidebar_item_key: fce
  alt_output_element_key: fuel_chain_emissions
  output_element_key: fuel_chain_emissions
