---
- group_sub_header: electricity_input
  key: flexibility_flexibility_power_storage
  position: 1
  sidebar_item_key: flexibility_storage
  alt_output_element_key: energy_storage
  output_element_key: flexibility_hourly_p2p_storage
- key: flexibility_power_storage_wind_turbine_inland
  position: 2
  sidebar_item_key: flexibility_storage
  output_element_key: flexibility_hourly_battery_wind
- key: flexibility_power_storage_solar_pv_solar_radiation
  position: 3
  sidebar_item_key: flexibility_storage
  output_element_key: flexibility_hourly_battery_solar
