---
- id: 180
  key: supply_primary_production_oil
  position: 3
  sidebar_item_key: fuel_production
  output_element_key: production_curve_crude_oil
- id: 181
  key: supply_primary_production_coal
  position: 2
  sidebar_item_key: fuel_production
  output_element_key: production_curve_coal
- id: 182
  key: supply_primary_production_natural_gas
  position: 4
  sidebar_item_key: fuel_production
  output_element_key: production_curve_natural_gas
- id: 184
  key: supply_primary_production_uranium
  position: 6
  sidebar_item_key: fuel_production
  output_element_key: production_curve_uranium
- id: 185
  key: supply_primary_production
  position: 1
  sidebar_item_key: fuel_production
  output_element_key: future_energy_imports
