---
- id: 277
  image: house_direct_heating.gif
  general_sub_header: heat_output
  key: supply_heat_sources
  position: 1
  sidebar_item_key: heat
  output_element_key: collective_heat_mekko
- id: 278
  key: supply_heat_network_storage_toggle
  position: 3
  sidebar_item_key: heat
  output_element_key: heat_network_storage
- id: 280
  key: supply_heat_network_losses
  position: 2
  sidebar_item_key: heat
  output_element_key: collective_heat_mekko
