---
- id: 26
  image: engine.gif
  general_sub_header: share
  key: demand_transport_truck_technology
  position: 12
  sidebar_item_key: transport_freight_transport
  output_element_key: use_of_final_demand_in_freight_transport_technologies
- id: 191
  general_sub_header: share
  key: demand_transport_domestic_navigation_technology
  position: 14
  sidebar_item_key: transport_freight_transport
  output_element_key: use_of_final_demand_in_freight_transport_technologies
- id: 229
  image: truck.gif
  general_sub_header: year
  group_sub_header: share
  key: demand_transport_freight_transport
  position: 11
  sidebar_item_key: transport_freight_transport
  output_element_key: use_of_final_demand_in_freight_transport
- id: 230
  general_sub_header: share
  key: demand_transport_freight_train_technology
  position: 13
  sidebar_item_key: transport_freight_transport
  output_element_key: use_of_final_demand_in_freight_transport_technologies
