---
- id: 24
  image: car.gif
  general_sub_header: "%/year"
  group_sub_header: share
  key: demand_transport_passenger_transport
  position: 1
  sidebar_item_key: transport_passenger_transport
  output_element_key: use_of_final_demand_in_passenger_transport
- id: 25
  image: engine.gif
  general_sub_header: share
  key: demand_transport_car_technology
  position: 2
  sidebar_item_key: transport_passenger_transport
  output_element_key: use_of_final_demand_in_cars
- id: 123
  general_sub_header: share
  key: demand_transport_domestic_aviation_technology
  position: 9
  sidebar_item_key: transport_passenger_transport
  output_element_key: use_of_final_demand_in_planes
- id: 125
  general_sub_header: share
  key: demand_transport_passenger_train_technology
  position: 3
  sidebar_item_key: transport_passenger_transport
  output_element_key: use_of_final_demand_in_busses_trains_and_trams
- id: 226
  general_sub_header: share
  key: demand_transport_bus_technology
  position: 6
  sidebar_item_key: transport_passenger_transport
  output_element_key: use_of_final_demand_in_busses_trains_and_trams
- id: 227
  general_sub_header: share
  key: demand_transport_bicycle_technology
  position: 8
  sidebar_item_key: transport_passenger_transport
  output_element_key: use_of_final_demand_in_motorcycles_and_bicycles
- id: 228
  general_sub_header: share
  key: demand_transport_motorcycle_technology
  position: 7
  sidebar_item_key: transport_passenger_transport
  output_element_key: use_of_final_demand_in_motorcycles_and_bicycles
- id: 234
  key: demand_transport_tram_technology
  position: 5
  sidebar_item_key: transport_passenger_transport
  output_element_key: use_of_final_demand_in_busses_trains_and_trams
