---
- key: households_insulation_level_apartments
  step_value: 0.1
  draw_to_min: 0.0
  unit: "%"
  position: 6
  slide_key: demand_households_insulation
- key: households_insulation_level_corner_houses
  step_value: 0.1
  draw_to_min: 0.0
  unit: "%"
  position: 7
  slide_key: demand_households_insulation
- key: households_insulation_level_detached_houses
  step_value: 0.1
  draw_to_min: 0.0
  unit: "%"
  position: 8
  slide_key: demand_households_insulation
- key: households_insulation_level_semi_detached_houses
  step_value: 0.1
  draw_to_min: 0.0
  unit: "%"
  position: 9
  slide_key: demand_households_insulation
- key: households_insulation_level_terraced_houses
  step_value: 0.1
  draw_to_min: 0.0
  unit: "%"
  position: 10
  slide_key: demand_households_insulation
