---
- key: households_useful_demand_for_cooling
  step_value: 0.1
  unit: "%"
  interface_group: per household
  position: 6
  slide_key: demand_households_demand_growth
- key: households_useful_demand_heat_per_person
  step_value: 0.1
  unit: "%"
  interface_group: per household
  position: 5
  slide_key: demand_households_demand_growth
- key: households_useful_demand_hot_water_share
  step_value: 0.1
  unit: "%"
  interface_group: per person
  position: 1
  slide_key: demand_households_demand_growth
- key: households_useful_demand_cooking_per_person
  step_value: 0.1
  unit: "%"
  interface_group: per person
  position: 4
  slide_key: demand_households_demand_growth
- key: households_useful_demand_electric_appliances
  step_value: 0.1
  unit: "%"
  interface_group: per person
  position: 2
  slide_key: demand_households_demand_growth
- key: households_useful_demand_lighting
  step_value: 0.1
  unit: "%"
  interface_group: per person
  position: 3
  slide_key: demand_households_demand_growth
