---
- key: households_lighting_efficient_fluorescent_electricity_share
  share_group: household_light
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: demand_households_lighting
- key: households_lighting_led_electricity_share
  share_group: household_light
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: demand_households_lighting
- key: households_lighting_incandescent_electricity_share
  share_group: household_light
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: demand_households_lighting
