---
- key: households_number_of_inhabitants
  step_value: 0.1
  unit: mln
  position: 0
  slide_key: demand_households_population
- key: households_apartments_share
  share_group: housing_stock
  step_value: 0.1
  unit: "%"
  interface_group: housing_stock
  position: 2
  slide_key: demand_households_population
- key: households_corner_houses_share
  share_group: housing_stock
  step_value: 0.1
  unit: "%"
  interface_group: housing_stock
  position: 3
  slide_key: demand_households_population
- key: households_detached_houses_share
  share_group: housing_stock
  step_value: 0.1
  unit: "%"
  interface_group: housing_stock
  position: 4
  slide_key: demand_households_population
- key: households_semi_detached_houses_share
  share_group: housing_stock
  step_value: 0.1
  unit: "%"
  interface_group: housing_stock
  position: 5
  slide_key: demand_households_population
- key: households_terraced_houses_share
  share_group: housing_stock
  step_value: 0.1
  unit: "%"
  interface_group: housing_stock
  position: 6
  slide_key: demand_households_population
- key: households_number_of_residences
  step_value: 1.0
  unit: "#"
  position: 1
  slide_key: demand_households_population
