development: &DEV
    # base url for api requests. This is used when CORS is enabled
    # (which is the default) or when the rails application runs a
    # local rack-based AJAX proxy
    api_url: https://beta-engine.energytransitionmodel.com

    # URL for the ETMoses application. ETMoses and testing ground features are
    # presently supported only when "api_url" is "http://beta.et-engine.com".
    etmoses_url: https://beta-moses.energytransitionmodel.com

    # URL for the Multi-Year Charts application.
    multi_year_charts_url: http://localhost:3005

    # This sets the url we use as API proxy. The proxying is handled
    # by nginx or a local rack-based proxy
    api_proxy_url: /ete_proxy

    # base url for partners api. This is used to retrieve the partner
    # names and such that are visible in the footer.
    partners_url: https://energytransitionmodel.com

    # google analytics key
    ga_tracker_code: 123456

    #  standalone instances are those such as the laptop. If set to true
    # the remote links and scripts will be disabled and the videos will
    # be played with a local player rather than vimeo/youtube. CORS will be
    # disabled, too
    standalone: false

    # URL that shows the gquery details (used on the charts admin page)
    # the gquery key is appended to the url
    gquery_detail_url: https://beta-engine.energytransitionmodel.com/data/latest/gqueries/key/

    # set to true if you want a "production server" warning in the admin section
    live_server: false

    # optional URL overrides for the splash screen links
    # mixer_url: http://mixer.et-model.com
    # etflex_url: http://light.et-model.com

    # Optionally send error messages to the Sentry service by providing your
    # Sentry DSN:
    sentry_dsn: false

    # Creating PDF versions of reports requires an external request back to the
    # app. This may not work in the development environments which run only a
    # single server process. Run a second instance of the app to prevent a
    # deadlock while fetching the HTML for the report.
    #
    # report_pdf_host: http://localhost:3000

production: &PRODUCTION
    <<: *DEV
test:
    <<: *DEV
    # set to true to pipe requests through the local proxy
    standalone: true
    etmoses_url: http://localhost:3002
    # WARNING: If you change this, the current 'vcr' cassettes (s. spec/cassettes/) will not be found -
    #          have to be manually adapted (s. spec_helper.rb -> default_cassette_options -> :record) or re-recorded
    api_url: https://beta-engine.energytransitionmodel.com
staging:
    <<: *PRODUCTION
