---
- key: employment_local_fraction
  step_value: 0.1
  unit: "%"
  command_type: value
  position: 2
  slide_key: costs_employment
- key: employment_economic_multiplier
  step_value: 0.1
  unit: x
  position: 3
  slide_key: costs_employment
- key: employment_fraction_production
  step_value: 0.1
  unit: "%"
  command_type: value
  position: 1
  slide_key: costs_employment
