---
- key: costs_heat_infra_indoors
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: costs_heat_network
- key: costs_heat_infra_outdoors
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: costs_heat_network
- key: costs_heat_network_storage
  step_value: 0.1
  unit: "€/MWh"
  interface_group: heat_network_storage
  position: 10
  slide_key: costs_heat_network
