---
- key: costs_oil
  step_value: 1.0
  unit: "$/barrel"
  position: 2
  slide_key: costs_combustion_fuel
- key: costs_coal
  step_value: 1.0
  unit: "$/tonne"
  position: 3
  slide_key: costs_combustion_fuel
- key: costs_gas
  step_value: 1.0
  unit: " €/MWh"
  command_type: value
  position: 1
  slide_key: costs_combustion_fuel
