---
- key: industry_aggregated_other_industry_wood_pellets_share
  share_group: other_industry_energetic
  step_value: 0.1
  unit: "%"
  interface_group: other_industry_energetic
  position: 1
  slide_key: demand_industry_aggregated_other
- key: industry_aggregated_other_industry_electricity_share
  share_group: other_industry_energetic
  step_value: 0.1
  unit: "%"
  interface_group: other_industry_energetic
  position: 2
  slide_key: demand_industry_aggregated_other
- key: industry_aggregated_other_industry_crude_oil_share
  share_group: other_industry_energetic
  step_value: 0.1
  unit: "%"
  interface_group: other_industry_energetic
  position: 3
  slide_key: demand_industry_aggregated_other
- key: industry_aggregated_other_industry_network_gas_share
  share_group: other_industry_energetic
  step_value: 0.1
  unit: "%"
  interface_group: other_industry_energetic
  position: 4
  slide_key: demand_industry_aggregated_other
- key: industry_aggregated_other_industry_coal_share
  share_group: other_industry_energetic
  step_value: 0.1
  unit: "%"
  interface_group: other_industry_energetic
  position: 5
  slide_key: demand_industry_aggregated_other
- key: industry_aggregated_other_industry_useable_heat_share
  share_group: other_industry_energetic
  step_value: 0.1
  unit: "%"
  interface_group: other_industry_energetic
  position: 6
  slide_key: demand_industry_aggregated_other
- key: industry_useful_demand_for_aggregated_other
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: demand_industry_aggregated_other
- key: industry_aggregated_other_industry_hydrogen_share
  share_group: other_industry_energetic
  step_value: 0.1
  unit: "%"
  interface_group: other_industry_energetic
  position: 0
  slide_key: demand_industry_aggregated_other
