---
- key: transport_freight_train_using_electricity_share
  share_group: transport_freight_train_share
  step_value: 0.1
  unit: "%"
  command_type: value
  position: 1
  related_node: transport_freight_train_using_electricity
  slide_key: demand_transport_freight_train_technology
- key: transport_freight_train_using_hydrogen_share
  share_group: transport_freight_train_share
  step_value: 0.1
  unit: "%"
  command_type: value
  position: 2
  related_node: transport_freight_train_using_hydrogen
  slide_key: demand_transport_freight_train_technology
- key: transport_freight_train_using_diesel_mix_share
  share_group: transport_freight_train_share
  step_value: 0.1
  unit: "%"
  command_type: value
  related_node: transport_freight_train_using_diesel_mix
  position: 3
  slide_key: demand_transport_freight_train_technology
