---
- key: number_of_buildings
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: demand_buildings_demand_growth
- key: buildings_useful_demand_electricity
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: demand_buildings_demand_growth
- key: buildings_useful_demand_for_space_heating
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: demand_buildings_demand_growth
- key: buildings_useful_demand_cooling
  step_value: 0.1
  unit: "%"
  position: 4
  slide_key: demand_buildings_demand_growth
