---
- key: transport_ship_using_diesel_mix_share
  share_group: transport_marine
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: demand_transport_domestic_navigation_technology
- key: transport_ship_using_lng_mix_share
  share_group: transport_marine
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: demand_transport_domestic_navigation_technology
