---
- key: transport_truck_using_electricity_share
  share_group: transport_truck_tech
  step_value: 0.1
  unit: "%"
  position: 1
  related_node: transport_truck_using_electricity
  slide_key: demand_transport_truck_technology
- key: transport_truck_using_hydrogen_share
  share_group: transport_truck_tech
  step_value: 0.1
  unit: "%"
  position: 2
  related_node: transport_truck_using_hydrogen
  slide_key: demand_transport_truck_technology
- key: transport_truck_using_diesel_mix_share
  share_group: transport_truck_tech
  step_value: 0.1
  unit: "%"
  position: 3
  related_node: transport_truck_using_diesel_mix
  slide_key: demand_transport_truck_technology
- key: transport_truck_using_gasoline_mix_share
  share_group: transport_truck_tech
  step_value: 0.1
  unit: "%"
  position: 4
  related_node: transport_truck_using_gasoline_mix
  slide_key: demand_transport_truck_technology
- key: transport_truck_using_lng_mix_share
  share_group: transport_truck_tech
  step_value: 0.1
  unit: "%"
  position: 5
  related_node: transport_truck_using_lng_mix
  slide_key: demand_transport_truck_technology
- key: transport_truck_using_compressed_natural_gas_share
  share_group: transport_truck_tech
  step_value: 0.1
  unit: "%"
  command_type: value
  position: 6
  related_node: transport_truck_using_compressed_natural_gas
  slide_key: demand_transport_truck_technology
