---
- key: gas_from_nederlands_share
  share_group: gas_lce
  step_value: 0.1
  unit: "%"
  interface_group: pipeline_natural_gas
  position: 2
  slide_key: fce_gas
- key: gas_from_russia_share
  share_group: gas_lce
  step_value: 0.1
  unit: "%"
  interface_group: pipeline_natural_gas
  position: 4
  slide_key: fce_gas
- key: gas_from_norway_share
  share_group: gas_lce
  step_value: 0.1
  unit: "%"
  interface_group: pipeline_natural_gas
  position: 3
  slide_key: fce_gas
- key: gas_from_algeria_share
  share_group: gas_lce
  step_value: 0.1
  unit: "%"
  interface_group: pipeline_natural_gas
  position: 1
  slide_key: fce_gas
- key: lng_from_algeria_share
  share_group: lng_fce
  step_value: 0.1
  unit: "%"
  interface_group: liquefied_natural_gas
  position: 5
  slide_key: fce_gas
- key: lng_from_norway_share
  share_group: lng_fce
  step_value: 0.1
  unit: "%"
  interface_group: liquefied_natural_gas
  position: 6
  slide_key: fce_gas
- key: lng_from_qatar_share
  share_group: lng_fce
  step_value: 0.1
  unit: "%"
  interface_group: liquefied_natural_gas
  position: 7
  slide_key: fce_gas
- key: lng_from_trinidad_share
  share_group: lng_fce
  step_value: 0.1
  unit: "%"
  interface_group: liquefied_natural_gas
  position: 8
  slide_key: fce_gas
