---
- key: uranium_from_kazachstan_share
  share_group: nuclear_lce
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: fce_uranium
- key: uranium_from_australia_share
  share_group: nuclear_lce
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: fce_uranium
- key: uranium_from_canada_share
  share_group: nuclear_lce
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: fce_uranium
