---
- key: coal_from_south_africa_share
  share_group: coal_lce
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: fce_coal
- key: coal_from_north_america_share
  share_group: coal_lce
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: fce_coal
- key: coal_from_australia_share
  share_group: coal_lce
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: fce_coal
- key: coal_from_eastern_europe_share
  share_group: coal_lce
  step_value: 0.1
  unit: "%"
  position: 4
  slide_key: fce_coal
- key: coal_from_russia_share
  share_group: coal_lce
  step_value: 0.1
  unit: "%"
  position: 5
  slide_key: fce_coal
- key: coal_from_south_america_share
  share_group: coal_lce
  step_value: 0.1
  unit: "%"
  position: 6
  slide_key: fce_coal
- key: coal_from_east_asia_share
  share_group: coal_lce
  step_value: 0.1
  unit: "%"
  position: 7
  slide_key: fce_coal
