---
- key: co2_emissions_of_imported_electricity_present
  step_value: 1.0
  unit: g/kWh
  position: 0
  slide_key: flexibility_electricity_import_export_properties
- key: co2_emissions_of_imported_electricity_future
  step_value: 1.0
  unit: g/kWh
  position: 1
  slide_key: flexibility_electricity_import_export_properties
