---
- key: interconnectors_availability_for_export
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: flexibility_electricity_import_export_interconnectivity
- key: interconnectors_availability_for_import
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: flexibility_electricity_import_export_interconnectivity
- key: interconnectors_interconnector_capacity
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: flexibility_electricity_import_export_interconnectivity
