---
- key: households_flexibility_space_heating_buffer_size_heatpump_air_water_electricity
  step_value: 0.5
  unit: kWh
  interface_group: flexibility_buffers_space
  position: 1
  slide_key: flexibility_flexibility_demand_response_hp
- key: households_flexibility_water_heating_buffer_size_heatpump_air_water_electricity
  step_value: 0.5
  unit: kWh
  interface_group: flexibility_buffers_water
  position: 1
  slide_key: flexibility_flexibility_demand_response_hp
- key: households_flexibility_space_heating_buffer_size_heatpump_ground_water_electricity
  step_value: 0.5
  unit: kWh
  interface_group: flexibility_buffers_space
  position: 2
  slide_key: flexibility_flexibility_demand_response_hp
- key: households_flexibility_space_heating_buffer_size_hybrid_heatpump_air_water_electricity
  step_value: 0.5
  unit: kWh
  interface_group: flexibility_buffers_space
  position: 3
  slide_key: flexibility_flexibility_demand_response_hp
- key: households_flexibility_water_heating_buffer_size_heatpump_ground_water_electricity
  step_value: 0.5
  unit: kWh
  interface_group: flexibility_buffers_water
  position: 2
  slide_key: flexibility_flexibility_demand_response_hp
- key: households_flexibility_water_heating_buffer_size_hybrid_heatpump_air_water_electricity
  step_value: 0.5
  unit: kWh
  interface_group: flexibility_buffers_water
  position: 3
  slide_key: flexibility_flexibility_demand_response_hp
