---
- key: policy_area_onshore_land
  step_value: 1.0
  unit: km2
  position: 1
  slide_key: policy_area_wind_turbines
- key: policy_area_onshore_coast
  step_value: 1.0
  unit: km
  position: 2
  dependent_on: has_coastline
  slide_key: policy_area_wind_turbines
- key: policy_area_offshore
  step_value: 1.0
  unit: km2
  position: 3
  dependent_on: has_coastline
  slide_key: policy_area_wind_turbines
