---
- key: policy_dependence_max_dependence
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: policy_dependence_foreign_dependence
- key: policy_dependence_max_electricity_dependence
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: policy_dependence_foreign_dependence
