- key: households_diesel_in_crude_oil_share
  share_group: households_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: households_oil_mix
  position: 1
  slide_key: supply_oil_mix
- key: households_biodiesel_in_crude_oil_share
  share_group: households_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: households_oil_mix
  position: 2
  slide_key: supply_oil_mix
- key: households_kerosene_in_crude_oil_share
  share_group: households_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: households_oil_mix
  position: 3
  slide_key: supply_oil_mix
- key: households_bio_kerosene_in_crude_oil_share
  share_group: households_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: households_oil_mix
  position: 4
  slide_key: supply_oil_mix
- key: households_lpg_in_crude_oil_share
  share_group: households_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: households_oil_mix
  position: 5
  slide_key: supply_oil_mix
- key: households_other_oil_in_crude_oil_share
  share_group: households_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: households_oil_mix
  position: 6
  slide_key: supply_oil_mix
- key: households_other_bio_oil_in_crude_oil_share
  share_group: households_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: households_oil_mix
  position: 7
  slide_key: supply_oil_mix
