- key: households_diesel_in_crude_oil_share
  share_group: households_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: households_oil_mix
  position: 1
  slide_key: supply_oil_mix
- key: households_biodiesel_in_crude_oil_share
  share_group: households_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: households_oil_mix
  position: 2
  slide_key: supply_oil_mix
- key: households_kerosene_in_crude_oil_share
  share_group: households_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: households_oil_mix
  position: 3
  slide_key: supply_oil_mix
- key: households_bio_kerosene_in_crude_oil_share
  share_group: households_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: households_oil_mix
  position: 4
  slide_key: supply_oil_mix
- key: households_lpg_in_crude_oil_share
  share_group: households_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: households_oil_mix
  position: 5
  slide_key: supply_oil_mix
- key: households_other_oil_in_crude_oil_share
  share_group: households_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: households_oil_mix
  position: 6
  slide_key: supply_oil_mix
- key: households_other_bio_oil_in_crude_oil_share
  share_group: households_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: households_oil_mix
  position: 7
  slide_key: supply_oil_mix
- key: buildings_diesel_in_crude_oil_share
  share_group: buildings_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: buildings_oil_mix
  position: 1
  slide_key: supply_oil_mix
- key: buildings_biodiesel_in_crude_oil_share
  share_group: buildings_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: buildings_oil_mix
  position: 2
  slide_key: supply_oil_mix
- key: buildings_kerosene_in_crude_oil_share
  share_group: buildings_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: buildings_oil_mix
  position: 3
  slide_key: supply_oil_mix
- key: buildings_bio_kerosene_in_crude_oil_share
  share_group: buildings_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: buildings_oil_mix
  position: 4
  slide_key: supply_oil_mix
- key: buildings_lpg_in_crude_oil_share
  share_group: buildings_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: buildings_oil_mix
  position: 5
  slide_key: supply_oil_mix
- key: buildings_other_oil_in_crude_oil_share
  share_group: buildings_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: buildings_oil_mix
  position: 6
  slide_key: supply_oil_mix
- key: buildings_other_bio_oil_in_crude_oil_share
  share_group: buildings_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: buildings_oil_mix
  position: 7
  slide_key: supply_oil_mix
- key: agriculture_diesel_in_crude_oil_share
  share_group: agriculture_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: agriculture_oil_mix
  position: 1
  slide_key: supply_oil_mix
- key: agriculture_biodiesel_in_crude_oil_share
  share_group: agriculture_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: agriculture_oil_mix
  position: 2
  slide_key: supply_oil_mix
- key: agriculture_kerosene_in_crude_oil_share
  share_group: agriculture_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: agriculture_oil_mix
  position: 3
  slide_key: supply_oil_mix
- key: agriculture_bio_kerosene_in_crude_oil_share
  share_group: agriculture_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: agriculture_oil_mix
  position: 4
  slide_key: supply_oil_mix
- key: agriculture_lpg_in_crude_oil_share
  share_group: agriculture_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: agriculture_oil_mix
  position: 5
  slide_key: supply_oil_mix
- key: agriculture_other_oil_in_crude_oil_share
  share_group: agriculture_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: agriculture_oil_mix
  position: 6
  slide_key: supply_oil_mix
- key: agriculture_other_bio_oil_in_crude_oil_share
  share_group: agriculture_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: agriculture_oil_mix
  position: 7
  slide_key: supply_oil_mix
- key: industry_diesel_in_crude_oil_share
  share_group: industry_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: industry_oil_mix
  position: 1
  slide_key: supply_oil_mix
- key: industry_biodiesel_in_crude_oil_share
  share_group: industry_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: industry_oil_mix
  position: 2
  slide_key: supply_oil_mix
- key: industry_kerosene_in_crude_oil_share
  share_group: industry_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: industry_oil_mix
  position: 3
  slide_key: supply_oil_mix
- key: industry_bio_kerosene_in_crude_oil_share
  share_group: industry_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: industry_oil_mix
  position: 4
  slide_key: supply_oil_mix
- key: industry_lpg_in_crude_oil_share
  share_group: industry_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: industry_oil_mix
  position: 5
  slide_key: supply_oil_mix
- key: industry_other_oil_in_crude_oil_share
  share_group: industry_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: industry_oil_mix
  position: 6
  slide_key: supply_oil_mix
- key: industry_other_bio_oil_in_crude_oil_share
  share_group: industry_crude_oil
  step_value: 0.1
  unit: "%"
  interface_group: industry_oil_mix
  position: 7
  slide_key: supply_oil_mix

