---
- key: capacity_of_energy_heat_burner_coal
  step_value: 1.0
  unit: MW
  interface_group: dispatchable_heat
  related_converter: energy_heat_burner_coal
  position: 11
  dependent_on: has_coal_oil_for_heating_built_environment
  slide_key: supply_heat_network_storage_toggle
- key: heat_storage_enabled
  step_value: 1.0
  unit: boolean
  position: 1
  slide_key: supply_heat_network_storage_toggle
- key: energy_heat_network_storage_loss_share
  step_value: 0.1
  unit: "%"
  interface_group: heat_storage_losses
  position: 5
  slide_key: supply_heat_network_storage_toggle
