---
- key: max_demand_of_biogenic_waste
  step_value: 0.1
  unit: PJ
  position: 4
  slide_key: supply_biomass_potential
- key: max_demand_of_wet_biomass
  step_value: 0.1
  unit: PJ
  position: 1
  slide_key: supply_biomass_potential
- key: max_demand_of_dry_biomass
  step_value: 0.1
  unit: PJ
  position: 2
  slide_key: supply_biomass_potential
- key: max_demand_of_oily_biomass
  step_value: 0.1
  unit: PJ
  position: 3
  slide_key: supply_biomass_potential
