---
- key: transport_shipping_mixer_lng_lng_share
  share_group: transport_lng_ship
  step_value: 0.1
  unit: "%"
  interface_group: lng_shipping_mix
  position: 6
  slide_key: supply_transport_marine_fuels
- key: transport_shipping_mixer_lng_bio_lng_share
  share_group: transport_lng_ship
  step_value: 0.1
  unit: "%"
  interface_group: lng_shipping_mix
  position: 7
  slide_key: supply_transport_marine_fuels
- key: transport_shipping_mixer_diesel_diesel_share
  share_group: transport_diesel_ship
  step_value: 0.1
  unit: "%"
  interface_group: diesel_shipping_mix
  position: 1
  slide_key: supply_transport_marine_fuels
- key: transport_shipping_mixer_diesel_biodiesel_share
  share_group: transport_diesel_ship
  step_value: 0.1
  unit: "%"
  interface_group: diesel_shipping_mix
  position: 2
  slide_key: supply_transport_marine_fuels
- key: transport_shipping_mixer_diesel_lng_share
  share_group: transport_diesel_ship
  step_value: 0.1
  unit: "%"
  interface_group: diesel_shipping_mix
  position: 3
  slide_key: supply_transport_marine_fuels
- key: transport_shipping_mixer_diesel_bio_lng_share
  share_group: transport_diesel_ship
  step_value: 0.1
  unit: "%"
  interface_group: diesel_shipping_mix
  position: 4
  slide_key: supply_transport_marine_fuels
- key: transport_shipping_mixer_diesel_heavy_fuel_oil_share
  share_group: transport_diesel_ship
  step_value: 0.1
  unit: "%"
  interface_group: diesel_shipping_mix
  position: 5
  slide_key: supply_transport_marine_fuels
