---
- key: bunkers_allocated_percentage_aviation
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: demand_transport_international_transport
- key: bunkers_allocated_percentage_shipping
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: demand_transport_international_transport
