---
- key: transport_bicycle_using_human_power_share
  share_group: transport_bicycle_tech
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: demand_transport_bicycle_technology
- key: transport_bicycle_using_electricity_share
  share_group: transport_bicycle_tech
  step_value: 0.1
  unit: "%"
  command_type: value
  position: 2
  slide_key: demand_transport_bicycle_technology
