---
- key: transport_cars_share
  share_group: passenger_transport
  step_value: 0.1
  unit: "%"
  interface_group: empty
  position: 2
  slide_key: demand_transport_passenger_transport
- key: transport_passenger_trains_share
  share_group: passenger_transport
  step_value: 0.1
  unit: "%"
  interface_group: empty
  position: 3
  slide_key: demand_transport_passenger_transport
- key: transport_planes_share
  share_group: passenger_transport
  step_value: 0.1
  unit: "%"
  interface_group: empty
  position: 8
  slide_key: demand_transport_passenger_transport
- key: transport_useful_demand_passenger_kms
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: demand_transport_passenger_transport
- key: transport_busses_share
  share_group: passenger_transport
  step_value: 0.1
  unit: "%"
  interface_group: empty
  position: 5
  slide_key: demand_transport_passenger_transport
- key: transport_trams_share
  share_group: passenger_transport
  step_value: 0.1
  unit: "%"
  interface_group: empty
  position: 4
  slide_key: demand_transport_passenger_transport
- key: transport_bicycles_share
  share_group: passenger_transport
  step_value: 0.1
  unit: "%"
  interface_group: empty
  position: 7
  slide_key: demand_transport_passenger_transport
- key: transport_motorcycles_share
  share_group: passenger_transport
  step_value: 0.1
  unit: "%"
  interface_group: empty
  position: 6
  slide_key: demand_transport_passenger_transport
