---
- key: transport_car_using_electricity_share
  share_group: transport_car_tech
  step_value: 0.1
  unit: "%"
  command_type: value
  position: 1
  slide_key: demand_transport_car_technology
- key: transport_car_using_diesel_mix_share
  share_group: transport_car_tech
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: demand_transport_car_technology
- key: transport_car_using_gasoline_mix_share
  share_group: transport_car_tech
  step_value: 0.1
  unit: "%"
  position: 4
  slide_key: demand_transport_car_technology
- key: transport_car_using_lpg_share
  share_group: transport_car_tech
  step_value: 0.1
  unit: "%"
  position: 5
  slide_key: demand_transport_car_technology
- key: transport_car_using_compressed_natural_gas_share
  share_group: transport_car_tech
  step_value: 0.1
  unit: "%"
  position: 6
  slide_key: demand_transport_car_technology
- key: transport_car_using_hydrogen_share
  share_group: transport_car_tech
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: demand_transport_car_technology
